name: inception

# Docker Compose configuration
services:
  mariadb:
    networks:
      - inception_network
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
    secrets:
      - db_root_password
      - db_password
  wordpress:
    depends_on:
      - mariadb
    networks:
      - inception_network
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    env_file: .env
    ports:
      - "80:80"
    volumes:
      - wp_data:/var/www/html
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password

#costume network for the project
networks:
  inception_network:
    name: inception_network
    driver: bridge

# named volume for both mariadb and wordpress
volumes:
  db_data:
    driver_opts:
      type: none
      device: /home/sel/data/mysql
      o: bind
  wp_data:
    driver_opts:
      type: none
      device: /home/sel/data/wordpress
      o: bind

secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt
  db_password:
    file: ./secrets/db_password.txt
  wp_admin_password:
    file: ./secrets/wp_admin_password.txt
  wp_user_password:
    file: ./secrets/wp_user_password.txt