name: inception

# Docker Compose configuration
services:
  mariadb:
    image: mariadb:1
    networks:
      - inception_network
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
    secrets:
      - db_root_password
      - db_password
  redis:
    image: redis:1
    networks:
      - inception_network
    build: ./requirements/redis
    container_name: redis
    restart: always

  adminer:
    image: adminer:1
    depends_on:
      - mariadb
    networks:
      - inception_network
    build: ./requirements/adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"

  wordpress:
    image: wp:1
    depends_on:
      - mariadb
      - redis
    networks:
      - inception_network
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    env_file: .env
    volumes:
      - wp_data:/var/www/html
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
      
  nginx:
    image: nginx:1
    depends_on:
      - wordpress
    networks:
      - inception_network
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html
  
  static_page:
    image: not-gpt:1
    networks:
      - inception_network
    build: ./requirements/static_page
    container_name: static_page
    restart: always
    ports:
      - "3000:3000"
      
  game:
    image: game:1
    networks:
      - inception_network
    build: ./requirements/2048
    container_name: game
    restart: always
    ports:
      - "2048:8080"

  ftp:
    image: ftp:1
    depends_on:
      - wordpress
    networks:
      - inception_network
    build: ./requirements/ftp
    container_name: ftp
    restart: always
    env_file: .env
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    volumes:
      - wp_data:/var/www/html

#costume network for the project
networks:
  inception_network:
    name: inception_network
    driver: bridge

# named volume for both mariadb and wordpress
volumes:
  db_data:
    driver_opts:
      type: none
      device: /home/sel/data/mysql
      o: bind
  wp_data:
    driver_opts:
      type: none
      device: /home/sel/data/wordpress
      o: bind
  # portainer_data:
  #   driver_opts:
  #     type: none
  #     device: /home/sel/data/portainer
  #     o: bind
  # docker-sock:
  #   driver_opts:
  #     type: none
  #     device: /var/run/docker.sock
  #     o: bind

secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt
  db_password:
    file: ./secrets/db_password.txt
  wp_admin_password:
    file: ./secrets/wp_admin_password.txt
  wp_user_password:
    file: ./secrets/wp_user_password.txt