name: inception

# Docker Compose configuration
services:
  mariadb:
    networks:
      - inception_network
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql

#costume network for the project
networks:
  inception_network:
    name: inception_network
    driver: bridge

# named volume for both mariadb and wordpress
volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /home/sel/data/db
      o: bind
  wp_data:
    driver: local
    driver_opts:
      type: none
      device: /home/sel/data/wp
      o: bind